// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChrtGQfqMDvPX8BeOh3ZODSY-GoM8i70Q',
    appId: '1:1047294349653:web:c228f986ac52fdb5e61fdc',
    messagingSenderId: '1047294349653',
    projectId: 'schoolables-17abe',
    authDomain: 'schoolables-17abe.firebaseapp.com',
    storageBucket: 'schoolables-17abe.appspot.com',
    measurementId: 'G-TQ9R16GT2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo1dRRZEQHh48XqhgSd8-_MeMfu7mypx0',
    appId: '1:1047294349653:android:55c9103226fca512e61fdc',
    messagingSenderId: '1047294349653',
    projectId: 'schoolables-17abe',
    storageBucket: 'schoolables-17abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGbS8w4_k7rSSzJHYqKQcnFhh065Jj_pk',
    appId: '1:1047294349653:ios:21a0f10be7b5b292e61fdc',
    messagingSenderId: '1047294349653',
    projectId: 'schoolables-17abe',
    storageBucket: 'schoolables-17abe.appspot.com',
    iosClientId: '1047294349653-h4pnv3rn0uivemt9rndb8e3c0rfp4r29.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterdemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGbS8w4_k7rSSzJHYqKQcnFhh065Jj_pk',
    appId: '1:1047294349653:ios:21a0f10be7b5b292e61fdc',
    messagingSenderId: '1047294349653',
    projectId: 'schoolables-17abe',
    storageBucket: 'schoolables-17abe.appspot.com',
    iosClientId: '1047294349653-h4pnv3rn0uivemt9rndb8e3c0rfp4r29.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterdemo',
  );
}
